### ISSUE TITLE
HTML files should be properly minified on production builds

### ISSUE THREAD

**Issue by james7132** [HouraiTeahouse/houraiteahouse.net-frontend#29]
The produced HTML files on production builds still have excess whitespace and comments.  
~~The produced JavaScript still has comments.~~  
~~The produced CSS still has comments.~~

**Comment by gscoppino** [comment]
The default configuration for CSS/JS minification is to preserve comment blocks that are signified as important  with a bang character `!` e.g. `/*!` or `/**!` [[1]] [[2]]. The JS minifier also has a second check for any comments with `@preserve` or `@license`, and will preserve those as well [[1]]. All other comments in CSS/JS should be removed, and, from looking at the output of the production build, this appears to be the case (the only comments I see contain license information).

I do see that I didn't add minification of HTML, I will address that ASAP.

[1]: https://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin
[2]: http://cssnano.co/optimisations/discardComments/

**Comment by gscoppino** [comment]
Addressed by PR #43
