### ISSUE TITLE
Footer issues

### ISSUE THREAD

**Issue by james7132** [HouraiTeahouse/houraiteahouse.net-frontend#50]
- [x] Language select in footer does not expand
- [x] Language select sticks out like a sore thumb, needs a more nuanced look.
- [x] Footer is fixed. Probably should be sticky instead.
- [x] Text regarding copyright is also not visible.

**Comment by gscoppino** [comment]
>  Footer is sticky. Probably should be fixed instead (sticks to the bottom when content is smaller than the full view port, but should otherwise just be at the bottom of the page)

Just want to a make a quick note, what we have now is considered a "fixed" footer (as in, it is fixed to the bottom of the browser viewport). What you are asking for will be a "sticky" footer (is at the bottom of the viewport to start, but is pushed down as more content is added than can fit in the viewport). I will go ahead and make the changes necessary.

**Comment by james7132** [comment]
All resolved in #51
